### ISSUE TITLE
[Suggestion] Please keep the autotools based build system

### ISSUE THREAD

**Issue by ghost** [devinsmith/fox#15]
Currently, the original autotools based build system used by FOX Toolkit is removed and replaced with the CMake based build system. Yes, I know the purpose of this project is to provide a CMake based build system for the FOX Toolkit. But, what would happen when the CMake based build system not working? If you keep the autotools based build system, at least, the users will have something to fall back rather than having to download the official tarball.

**Comment by devinsmith** [comment]
It's not a bad idea but I am not sure I can maintain and test both build systems

**Comment by ghost** [comment]
> It's not a bad idea but I am not sure I can maintain and test both build systems

The autotools based build system is supposed to always work, as it's what officially provided by the FOX Toolkit project. So, I think you don't have to care about it. You only have to focus on CMake. The autotools based build system is always there as a fallback when CMake doesn't work.
