### ISSUE TITLE
CMake supports Windows?

### ISSUE THREAD

**Issue by wxinix** [devinsmith/fox#2]
Seems Windows is covered in the CMakeLists.txt?

Also can you shed some light on what the "control panel" folder is about?

Thank you

**Comment by devinsmith** [comment]
Yes, this library does support Windows but I haven't tried to build it with CMake on Windows. There might be some Linux-isms in the CMake files that need cleanup, but I'm not sure.

The control panel application is a tool to define the default color scheme and font that gets applied to all FOX applications. Otherwise FOX uses the default (a Windows 95-ish color scheme).

**Comment by wxinix** [comment]
Thank you.

**Comment by 3oheicrw** [comment]
> Yes, this library does support Windows but I haven't tried to build it with CMake on Windows. There might be some Linux-isms in the CMake files that need cleanup, but I'm not sure.
> 
> The control panel application is a tool to define the default color scheme and font that gets applied to all FOX applications. Otherwise FOX uses the default (a Windows 95-ish color scheme).

Yes. Some Linux-ism. Still expects freetype and fontconfig even though the Windows port of FOX doesn't use them. The library libopenjpeg1 is weird. I don't recall it as a dependency when I build FOX on Linux. So does libepoxy. Seems something new on FOX 1.7.78.

I'm using MSYS2. This is the list of packages needed to install:

mingw64/mingw-w64-x86_64-toolchain mingw64/mingw-w64-x86_64-cmake mingw64/mingw-w64-x86_64-ninja mingw64/mingw-w64-x86_64-libtiff mingw64/mingw-w64-x86_64-libepoxy mingw64/mingw-w64-x86_64-openjpeg

This satisfied cmake and you could try to build. Anyway, the build fails.

This is the error log:

```
FAILED: lib/CMakeFiles/fox.dir/fxjpegio.cpp.obj
C:\Extra\Compressed\msys64\mingw64\bin\c++.exe -DHAVE_BZ2LIB_H -DHAVE_DIRENT_H -DHAVE_EPOXY -DHAVE_GLU_H -DHAVE_GL_H -DHAVE_IMMINTRIN_H -DHAVE_JPEG_H -DHAVE_PNG_H -DHAVE_SEMAPHORE_H -DHAVE_SYS_PARAM_H -DHAVE_SYS_TIME_H -DHAVE_TIFF_H -DHAVE_UNISTD_H -DHAVE_WEBP_H -DHAVE_ZLIB_H -DTIME_WITH_SYS_TIME -IC:/Extra/Compressed/msys64/home/Administrator/fox/include  -MD -MT lib/CMakeFiles/fox.dir/fxjpegio.cpp.obj -MF lib\CMakeFiles\fox.dir\fxjpegio.cpp.obj.d -o lib/CMakeFiles/fox.dir/fxjpegio.cpp.obj -c C:/Extra/Compressed/msys64/home/Administrator/fox/lib/fxjpegio.cpp
In file included from C:/Extra/Compressed/msys64/mingw64/x86_64-w64-mingw32/include/wtypesbase.h:13,
                 from C:/Extra/Compressed/msys64/mingw64/x86_64-w64-mingw32/include/combaseapi.h:153,
                 from C:/Extra/Compressed/msys64/mingw64/x86_64-w64-mingw32/include/objbase.h:14,
                 from C:/Extra/Compressed/msys64/mingw64/x86_64-w64-mingw32/include/shlwapi.h:14,
                 from C:/Extra/Compressed/msys64/mingw64/include/jmorecfg.h:19,
                 from C:/Extra/Compressed/msys64/mingw64/include/jpeglib.h:31,
                 from C:/Extra/Compressed/msys64/home/Administrator/fox/lib/fxjpegio.cpp:38:
C:/Extra/Compressed/msys64/mingw64/x86_64-w64-mingw32/include/ole2.h:41:20: error: variable 'OleBuildVersion' definition is marked dllimport
   41 | WINOLEAPI_ (DWORD) OleBuildVersion (VOID);
      |                    ^~~~~~~~~~~~~~~
C:/Extra/Compressed/msys64/mingw64/x86_64-w64-mingw32/include/ole2.h:41:37: error: 'VOID' was not declared in this scope; did you mean 'PVOID'?
   41 | WINOLEAPI_ (DWORD) OleBuildVersion (VOID);
      |                                     ^~~~
      |                                     PVOID
In file included from C:/Extra/Compressed/msys64/mingw64/x86_64-w64-mingw32/include/shlwapi.h:14,
                 from C:/Extra/Compressed/msys64/mingw64/include/jmorecfg.h:19,
                 from C:/Extra/Compressed/msys64/mingw64/include/jpeglib.h:31,
                 from C:/Extra/Compressed/msys64/home/Administrator/fox/lib/fxjpegio.cpp:38:
C:/Extra/Compressed/msys64/mingw64/x86_64-w64-mingw32/include/objbase.h:79:19: error: variable 'CoBuildVersion' definition is marked dllimport
   79 | WINOLEAPI_(DWORD) CoBuildVersion (VOID);
      |                   ^~~~~~~~~~~~~~
C:/Extra/Compressed/msys64/mingw64/x86_64-w64-mingw32/include/objbase.h:79:35: error: 'VOID' was not declared in this scope; did you mean 'PVOID'?
   79 | WINOLEAPI_(DWORD) CoBuildVersion (VOID);
      |                                   ^~~~
      |                                   PVOID
```

Please reopen this ticket. Thanks.

**Comment by devinsmith** [comment]
Will reopen and investigate with GitHub actions

**Comment by devinsmith** [comment]
I believe this is now solved with Github actions and builds on Windows
