### ISSUE TITLE
Please update to FOX 1.7.82

### ISSUE THREAD

**Issue by ghost** [devinsmith/fox#9]

**Comment by devinsmith** [comment]
Addressing this in #11 

Also will update to 1.7.83 which came out today.

**Comment by ghost** [comment]
> Addressing this in #11
> 
> Also will update to 1.7.83 which came out today.

Thank you. Btw, 1.7.82 seems introduced support for CUPS so please add a check for CUPS on your CMakeLists.txt, if CUPS is available then add `-DHAVE_CUPS_H`.

Disclaimer: I have not checked the original autotools based build script yet, I got this information from https://github.com/franko/fox/commit/268674a0b9857996bf6783fd0462aa48a5fcd7eb
